const img = (file) => new URL(`../assets/images/${file}`, import.meta.url).href;

export const categories = [
  { id: 1, name: "Sepatu Kets" },
  { id: 2, name: "Sepatu Lari" },
  { id: 3, name: "Formal" },
  { id: 4, name: "Kasual" },
  { id: 5, name: "Bot" },
];

export const products = [
  {
    id: 1,
    name: "Urban Walker",
    slug: "urban-walker",
    price: 450000,
    stock: 12,
    category: 1,
    category_name: "Sepatu Kets",
    rating: 4,
    img: img("sepatu-01-urban-walker.jpg"),
    description: "Sepatu kets harian dengan sol empuk dan desain bersih yang cocok untuk kuliah maupun nongkrong.",
  },
  {
    id: 2,
    name: "Street Classic",
    slug: "street-classic",
    price: 520000,
    stock: 8,
    category: 1,
    category_name: "Sepatu Kets",
    rating: 5,
    img: img("sepatu-02-street-classic.jpg"),
    description: "Sepatu kets bergaya klasik dengan bahan kuat dan mudah dipadukan dengan pakaian apa pun.",
  },
  {
    id: 3,
    name: "Swift Runner",
    slug: "swift-runner",
    price: 680000,
    stock: 15,
    category: 2,
    category_name: "Sepatu Lari",
    rating: 5,
    img: img("sepatu-03-swift-runner.jpg"),
    description: "Sepatu lari ringan dengan bantalan responsif dan bahan berpori agar kaki tetap nyaman.",
  },
  {
    id: 4,
    name: "Trail Max",
    slug: "trail-max",
    price: 750000,
    stock: 0,
    category: 2,
    category_name: "Sepatu Lari",
    rating: 4,
    img: img("sepatu-04-trail-max.jpg"),
    description: "Sepatu lari medan alam dengan cengkeraman kuat untuk jalur yang tidak rata.",
  },
  {
    id: 5,
    name: "Oxford Prime",
    slug: "oxford-prime",
    price: 890000,
    stock: 6,
    category: 3,
    category_name: "Formal",
    rating: 5,
    img: img("sepatu-05-oxford-prime.jpg"),
    description: "Sepatu formal kulit sintetis premium untuk presentasi, wawancara, dan acara resmi.",
  },
  {
    id: 6,
    name: "Derby Elegant",
    slug: "derby-elegant",
    price: 820000,
    stock: 4,
    category: 3,
    category_name: "Formal",
    rating: 4,
    img: img("sepatu-06-derby-elegant.jpg"),
    description: "Sepatu pantofel dengan jahitan rapi dan sol nyaman untuk dipakai seharian.",
  },
  {
    id: 7,
    name: "Slip-On Easy",
    slug: "slip-on-easy",
    price: 320000,
    stock: 20,
    category: 4,
    category_name: "Kasual",
    rating: 4,
    img: img("sepatu-07-slip-on-easy.jpg"),
    description: "Sepatu selop praktis tanpa tali, ringan dan cocok untuk aktivitas santai.",
  },
  {
    id: 8,
    name: "Canvas Daily",
    slug: "canvas-daily",
    price: 280000,
    stock: 3,
    category: 4,
    category_name: "Kasual",
    rating: 3,
    img: img("sepatu-08-canvas-daily.jpg"),
    description: "Sepatu kanvas simpel dengan banyak pilihan gaya untuk keseharian.",
  },
  {
    id: 9,
    name: "Skyline High",
    slug: "skyline-high",
    price: 580000,
    stock: 10,
    category: 1,
    category_name: "Sepatu Kets",
    rating: 4,
    img: img("sepatu-09-skyline-high.jpg"),
    description: "Sepatu kets model tinggi dengan bantalan tebal dan siluet tegas untuk gaya jalanan.",
  },
  {
    id: 10,
    name: "Retro Court",
    slug: "retro-court",
    price: 495000,
    stock: 14,
    category: 1,
    category_name: "Sepatu Kets",
    rating: 5,
    img: img("sepatu-10-retro-court.jpg"),
    description: "Sepatu kets bergaya lapangan klasik dengan sol karet yang awet dan nyaman.",
  },
  {
    id: 11,
    name: "Aero Sprint",
    slug: "aero-sprint",
    price: 720000,
    stock: 9,
    category: 2,
    category_name: "Sepatu Lari",
    rating: 5,
    img: img("sepatu-11-aero-sprint.jpg"),
    description: "Sepatu lari super ringan untuk kecepatan, dengan sol yang responsif.",
  },
  {
    id: 12,
    name: "Pace Lite",
    slug: "pace-lite",
    price: 560000,
    stock: 18,
    category: 2,
    category_name: "Sepatu Lari",
    rating: 4,
    img: img("sepatu-12-pace-lite.jpg"),
    description: "Sepatu lari harian dengan bantalan empuk untuk jarak menengah.",
  },
  {
    id: 13,
    name: "Loafer Classic",
    slug: "loafer-classic",
    price: 760000,
    stock: 7,
    category: 3,
    category_name: "Formal",
    rating: 4,
    img: img("sepatu-13-loafer-classic.jpg"),
    description: "Sepatu selop kulit sintetis tanpa tali yang rapi untuk kantor dan acara semiformal.",
  },
  {
    id: 14,
    name: "Weekend Moc",
    slug: "weekend-moc",
    price: 340000,
    stock: 16,
    category: 4,
    category_name: "Kasual",
    rating: 4,
    img: img("sepatu-14-weekend-moc.jpg"),
    description: "Sepatu mokasin santai yang ringan untuk jalan-jalan akhir pekan.",
  },
  {
    id: 15,
    name: "Hiker Pro",
    slug: "hiker-pro",
    price: 850000,
    stock: 5,
    category: 5,
    category_name: "Bot",
    rating: 5,
    img: img("sepatu-15-hiker-pro.jpg"),
    description: "Bot luar ruangan tahan air dengan sol bergerigi untuk jalur mendaki.",
  },
  {
    id: 16,
    name: "Chelsea Daily",
    slug: "chelsea-daily",
    price: 690000,
    stock: 11,
    category: 5,
    category_name: "Bot",
    rating: 4,
    img: img("sepatu-16-chelsea-daily.jpg"),
    description: "Bot dengan karet elastis di samping, mudah dipakai dan cocok untuk gaya kasual yang rapi.",
  },
];

export const heroImage = img("hero-banner.jpg");